name: "Generate XML"

on:
  # Schedule updates
  schedule: [{cron: "0 10/6 * * *"}]
  push: 
    branches: 
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip3 install -r requirements.txt
      
      - name: Run Generator
        env:
          RSS_LINK: https://chand1012.github.io/static-rss-generator/feed.xml
        run: python3 main.py

      - name: Update Feed
        run: |
          git config user.name "Github Action"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mv feed.xml temp-feed.xml
          git fetch
          git checkout gh-pages
          rm feed.xml
          mv temp-feed.xml feed.xml
          if [ -n "$(git status --porcelain)" ]; then
            echo "there are changes";
            git commit -am "[bot] Update static files." 
            git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
            git push origin gh-pages
          else
            echo "no changes";
          fi
          



          
